name = "Gamess"
uuid = "529696b1-8e09-48fc-adc2-b2323c86ff90"
authors = ["Stefanos Carlström <stefanos.carlstrom@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DataFrames = "0.21"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
